apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-monitoring
  template:
    metadata:
      labels:
        app: system-monitoring
    spec:
      containers:
        - name: system-monitoring-container
          image: chndra/cpumoniter:latest
          ports:
            - containerPort: 5000
